//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.RateCalculatorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRate", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        private float RateAdjustmentField;
        
        private double RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Program {
            get {
                return this.ProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramField, value) != true)) {
                    this.ProgramField = value;
                    this.RaisePropertyChanged("Program");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float RateAdjustment {
            get {
                return this.RateAdjustmentField;
            }
            set {
                if ((this.RateAdjustmentField.Equals(value) != true)) {
                    this.RateAdjustmentField = value;
                    this.RaisePropertyChanged("RateAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RateCalculatorServiceReference.RateCalculatorWebServiceSoap")]
    public interface RateCalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetLowestRateByDateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLowestRateByDate", ReplyAction="*")]
        UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse GetLowestRateByDate(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLowestRateByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse> GetLowestRateByDateAsync(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLowestRateByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLowestRateByDate", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequestBody Body;
        
        public GetLowestRateByDateRequest() {
        }
        
        public GetLowestRateByDateRequest(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLowestRateByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime strPeriodStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime strPeriodEnd;
        
        public GetLowestRateByDateRequestBody() {
        }
        
        public GetLowestRateByDateRequestBody(System.DateTime strPeriodStart, System.DateTime strPeriodEnd) {
            this.strPeriodStart = strPeriodStart;
            this.strPeriodEnd = strPeriodEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLowestRateByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLowestRateByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponseBody Body;
        
        public GetLowestRateByDateResponse() {
        }
        
        public GetLowestRateByDateResponse(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLowestRateByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject.RateCalculatorServiceReference.ProductRate GetLowestRateByDateResult;
        
        public GetLowestRateByDateResponseBody() {
        }
        
        public GetLowestRateByDateResponseBody(UnitTestProject.RateCalculatorServiceReference.ProductRate GetLowestRateByDateResult) {
            this.GetLowestRateByDateResult = GetLowestRateByDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RateCalculatorWebServiceSoapChannel : UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateCalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap>, UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap {
        
        public RateCalculatorWebServiceSoapClient() {
        }
        
        public RateCalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RateCalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateCalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateCalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap.GetLowestRateByDate(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest request) {
            return base.Channel.GetLowestRateByDate(request);
        }
        
        public UnitTestProject.RateCalculatorServiceReference.ProductRate GetLowestRateByDate(System.DateTime strPeriodStart, System.DateTime strPeriodEnd) {
            UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest inValue = new UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest();
            inValue.Body = new UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequestBody();
            inValue.Body.strPeriodStart = strPeriodStart;
            inValue.Body.strPeriodEnd = strPeriodEnd;
            UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse retVal = ((UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap)(this)).GetLowestRateByDate(inValue);
            return retVal.Body.GetLowestRateByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse> UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap.GetLowestRateByDateAsync(UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest request) {
            return base.Channel.GetLowestRateByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateResponse> GetLowestRateByDateAsync(System.DateTime strPeriodStart, System.DateTime strPeriodEnd) {
            UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest inValue = new UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequest();
            inValue.Body = new UnitTestProject.RateCalculatorServiceReference.GetLowestRateByDateRequestBody();
            inValue.Body.strPeriodStart = strPeriodStart;
            inValue.Body.strPeriodEnd = strPeriodEnd;
            return ((UnitTestProject.RateCalculatorServiceReference.RateCalculatorWebServiceSoap)(this)).GetLowestRateByDateAsync(inValue);
        }
    }
}
